appvendas/urls.py
from django.conf.urls import patterns,include,url
from appvendas.views import *
urlpatterns=[
    url(r'^$',home,name='home'),
    url(r'^contato$',contato,name='contato'),

    url(r'^produto/list$',produto_list,name='produto_list'),
    url(r'^produto/detail/(?P<pk>\d+)$',produto_detail,name='produto_detail'),
    url(r'^produto/new/$',produto_new,name='produto_new'),
    url(r'^produto/update/(?P<pk>\d+)$',produto_update,name='produto_update'),
    url(r'^produto/delete/(?P<pk>\d+)$',produto_delete,name='produto_delete'),


    url(r'^unidade/list$', unidade_list, name='unidade_list'),
    url(r'^unidade/detail/(?P<pk>\d+)$', unidade_detail, name='unidade_detail'),
    url(r'^unidade/new/$',unidade_new,name='unidade_new'),
    url(r'^unidade/update/(?P<pk>\d+)$',unidade_update,name='unidade_update'),
    url(r'^unidade/delete/(?P<pk>\d+)$',unidade_delete,name='unidade_delete'),

    url(r'^funcionario/list$', funcionario_list, name='funcionario_list'),
    url(r'^funcionario/new/$',funcionario_new,name='funcionario_new'),
    url(r'^funcionario/update/(?P<pk>\d+)$',funcionario_update,name='funcionario_update'),
    url(r'^funcionario/detail/(?P<pk>\d+)$', funcionario_detail, name='funcionario_detail'),
    url(r'^funcionario/delete/(?P<pk>\d+)$',funcionario_delete,name='funcionario_delete'),


    url(r'^venda/list$',venda_list,name='venda_list'),

    url(r'^cliente/list$', cliente_list, name='cliente_list'),
    url(r'^cliente/detail/(?P<pk>\d+)$', cliente_detail, name='cliente_detail'),
    url(r'^clientes/new/$', cliente_new, name='cliente_new'),
    url(r'^clientes/update/(?P<pk>\d+)$', cliente_update, name='cliente_update'),
    url(r'^clientes/delete/(?P<pk>\d+)$', cliente_delete, name='cliente_delete'),

    url(r'^cargo/list$', cargo_list, name='cargo_list'),
    url(r'^cargo/new/$', cargo_new, name='cargo_new'),
    url(r'^cargo/update/(?P<pk>\d+)$', cargo_update, name='cargo_update'),
    url(r'^cargo/delete/(?P<pk>\d+)$', cargo_delete, name='cargo_delete'),
]

projetovendas/urls.py
from django.conf.urls import patterns,include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appvendas/',include('appvendas.urls'))
]

appvendas/models.py
from django.db import models

# Create your models here.

class Unidade(models.Model):
    descricao=models.CharField("Descrição",max_length=100)
    sigla=models.CharField("Sigla",max_length=5)
    def __str__(self):
        return "{0:s}-{1:s}".format(self.descricao,self.sigla)

class Cargo(models.Model):
    descricao=models.CharField("Descrição",max_length=150)
    def __str__(self):
        return self.descricao

class Pessoa(models.Model):
    nome=models.CharField("Nome",max_length=255)
    email=models.EmailField("E-Mail",max_length=200)
    telefone=models.CharField("Telefone",max_length=20)

    def __str__(self):
        return self.nome

class Cliente(Pessoa):
    endereco=models.CharField("Endereço",max_length=255)


class Funcionario(Pessoa):
    matricula=models.CharField("Matrícula",max_length=10,unique=True)
    cargo=models.ForeignKey(Cargo,on_delete=models.PROTECT,verbose_name="Cargo")

class Produto(models.Model):
    descricao=models.CharField("Descrição",max_length=255)
    valorUnitario=models.DecimalField("Valor Unitário",max_digits=10,decimal_places=2)
    unidade=models.ForeignKey(Unidade,on_delete=models.PROTECT,verbose_name="Unidade")

    def __str__(self):
        return self.descricao

class Venda(models.Model):
    dataVenda=models.DateField("Data da Venda")
    vendedor=models.ForeignKey(Funcionario,on_delete=models.PROTECT,verbose_name="Funcionário")
    cliente=models.ForeignKey(Cliente,on_delete=models.PROTECT,verbose_name="Cliente")
    produtos=models.ManyToManyField(Produto,through="VendaProduto")

    def __str__(self):
        return "{0:d}-{1:s}".format(self.id,self.dataVenda.strftime('%d/%m/%Y'))

    def calculaValorTotal(self):
        lista=VendaProduto.objects.filter(venda=self) # Filtra os itens vinculados a esta venda
        #total=0
        #for item in lista: # Percorre a lista de itens, calculando o valor unitário
        #    total=total + item.produto.valorUnitario * item.quantidade
        #return total

        resultado=lista.aggregate(total=models.Sum(models.F('produto__valorUnitario')*models.F('quantidade'),output_field=models.FloatField()))
        return resultado['total']

class VendaProduto(models.Model):
    venda=models.ForeignKey(Venda,on_delete=models.CASCADE)
    produto=models.ForeignKey(Produto,on_delete=models.PROTECT)
    quantidade=models.IntegerField("Quantidade")
    @property
    def subtotal(self):
        return self.produto.valorUnitario*self.quantidade

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Sistema de Vendas</title>

    <link rel="stylesheet" href="{% static "css/simple-sidebar.css" %}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="{% url 'home' %}">
                        SISCONV
                    </a>
                </li>
                <li>
                    <a href="{% url 'unidade_list' %}"> Unidades </a>
                </li>
                <li>
                    <a href="{% url 'cargo_list' %}"> Cargos</a>
                </li>
                <li>
                    <a href="{% url 'produto_list' %}"> Produtos</a>
                </li>
                <li>
                    <a href="{% url 'cliente_list' %}"> Clientes</a>
                </li>
                <li>
                    <a href="{% url 'funcionario_list' %}"> Funcionários</a>
                </li>
                <li>
                    <a href="{% url 'venda_list' %}"> Vendas</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}"> Cadastros</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                    <center><img src="{% static "img/SISCONV.png" %}"></center>
                        {% block conteudo %}
                            <center><h3>Bem vindo ao Sistema de Controle de Vendas</h3></center>
                            <hr>
                            <p><h4>
                            Aumente suas vendas e garanta mais eficiência e segurança ao seu negócio com o SISCONV, um sistema que oferece soluções de gestão inovadoras e integradas que permitem aos varejistas elevarem a competitividade e aumentarem as vendas com melhores margens e níveis de estoque.
                            </h4></p>
                            <p><h4>Para mais informações entre em contato com nosso RH.</h4></p>
                            <center><a href="{% url 'contato' %}" class="btn btn-warning">Entrar em contato</a></center>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <script
              src="https://code.jquery.com/jquery-3.1.0.js"
              integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk="
              crossorigin="anonymous"></script>
        

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>


</body>
</html>

templates/contato.html
{% extends 'base.html' %}
{% load static %}
{% block conteudo %}
	<center><h2>Contato</h2></center>
	<hr>
	<center><img src="{% static 'img/eLw7m.gif' %}"></center>
{% endblock %}

templates/vendas.html
{% extends 'base.html' %}

{% block conteudo %}
    <center><h2>Vendas</h2></center>
    <hr>
    <p><a href="#" class="btn btn-primary" >Realizar nova venda</a></p>
    
      <table class="table table-bordered table-hover table-condensed">
        <tr>
          <th>Venda</th>
          <th>Cliente</th>
          <th>Funcionário</th>
          <th>Data da venda</th>
          <th>Itens da venda</th>
        </tr>  
        {% for venda in vendas  %}
          <tr>
            <td>{{venda.id}}</td>
            <td>{{venda.cliente.nome}}</td>
            <td>{{ venda.vendedor.nome }}</td>
            <td>{{ venda.dataVenda|date:'d/m/Y'  }}</td>
            <td>
              {% for item in venda.vendaproduto_set.all %}
                  <p>{{ item.quantidade }} x {{ item.produto.descricao }}</p>
                  <p>Preço da unidade :{{ item.produto.valorUnitario }} R$</p>
                  <p>Subtotal: {{item.subtotal}} R$</p>
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
      </table>
  
{% endblock %}